"""add privacy and encryption metadata

Revision ID: e6db49a35695
Revises: 0c6d6af6c689
Create Date: 2026-10-03 17:31:12.895560
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e6db49a35695"
down_revision: str | None = "0c6d6af6c689"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column(
        "attachments",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column("audit_logs", sa.Column("target_profile_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_audit_logs_target_profile_created_at",
        "audit_logs",
        ["target_profile_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "badge_awards",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column(
        "diet_plans",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column(
        "emergency_contacts",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column(
        "goals",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column(
        "health_records",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column(
        "reminders",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column("share_grants", sa.Column("record_id", sa.Uuid(), nullable=True))
    op.add_column(
        "share_grants",
        sa.Column("access_role", sa.String(length=32), server_default="viewer", nullable=False),
    )
    op.add_column(
        "sos_events",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column("users", sa.Column("wrapped_data_key", sa.LargeBinary(), nullable=True))
    op.add_column("users", sa.Column("data_key_nonce", sa.LargeBinary(), nullable=True))
    op.add_column("users", sa.Column("data_key_version", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        op.execute(
            """
            CREATE TRIGGER audit_logs_reject_update
            BEFORE UPDATE ON audit_logs
            BEGIN
                SELECT RAISE(ABORT, 'audit_logs are append-only');
            END
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_logs_reject_delete
            BEFORE DELETE ON audit_logs
            BEGIN
                SELECT RAISE(ABORT, 'audit_logs are append-only');
            END
            """
        )
    elif dialect == "postgresql":
        op.execute(
            """
            CREATE FUNCTION reject_audit_log_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs are append-only';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_logs_reject_mutation
            BEFORE UPDATE OR DELETE ON audit_logs
            FOR EACH ROW EXECUTE FUNCTION reject_audit_log_mutation()
            """
        )
    else:
        raise RuntimeError(f"Unsupported database dialect for audit immutability: {dialect}")


def downgrade() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS audit_logs_reject_update")
        op.execute("DROP TRIGGER IF EXISTS audit_logs_reject_delete")
    elif dialect == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_logs_reject_mutation ON audit_logs")
        op.execute("DROP FUNCTION IF EXISTS reject_audit_log_mutation()")
    else:
        raise RuntimeError(f"Unsupported database dialect for audit immutability: {dialect}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "data_key_version")
    op.drop_column("users", "data_key_nonce")
    op.drop_column("users", "wrapped_data_key")
    op.drop_column("sos_events", "visibility")
    op.drop_column("share_grants", "access_role")
    op.drop_column("share_grants", "record_id")
    op.drop_column("reminders", "visibility")
    op.drop_column("health_records", "visibility")
    op.drop_column("goals", "visibility")
    op.drop_column("emergency_contacts", "visibility")
    op.drop_column("diet_plans", "visibility")
    op.drop_column("badge_awards", "visibility")
    op.drop_index("ix_audit_logs_target_profile_created_at", table_name="audit_logs")
    op.drop_column("audit_logs", "target_profile_id")
    op.drop_column("attachments", "visibility")
    op.drop_column("appointments", "visibility")
    # ### end Alembic commands ###
